name: Sync with Upstream and Generate Docs

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM UTC
  workflow_dispatch:     # Optional: allows you to trigger it manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # we’ll use a token instead

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Zie619/n8n-workflows.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Generate workflow documentation
        run: |
          python3 generate_documentation.py

      - name: Commit and Push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "🛠 Sync from upstream and update docs" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/axiradigital/n8n-workflows.git main
